### ISSUE TITLE
Improve contribution guidelines

### ISSUE THREAD

**Issue by adiaholic** [The-Codesis/simple-static-website#27]
Current contribution guidelines suggests use of `git merge` on master after fetching upstream. There is another way to update master through `git rebase`.

To solve this issue:
- [ ]  Do some self research and state differences between both commands and make the explanation apparent in commit message.
- [ ] Mention these intricacies in contribution guidelines.
- [ ] Add reasons explaining which command is preferred.

**Comment by pranshi112** [comment]
Can I work on this issue?

**Comment by rahul799** [comment]
Go ahead
