### ISSUE TITLE
Develop a full-fledged website for Codesis

### ISSUE THREAD

**Issue by und3fined-v01d** [The-Codesis/simple-static-website#3]
**Is your feature request related to a problem? Please describe.**
Rather than have a boiler-plate static site, our aim should be to have a more concrete website that enables us to add events as and how we want. 

**Describe the solution you'd like**
It need not have a backend. `Gatsby` with `gatsby-transformer-yml` can be used. We will simply submit the events as a `yaml` file and a graphql query should automatically fetch the latest events using a filter.

**Additional context**
This will be a good exercise for beginners to immediately get well-versed with React and Gatsby. No prior knowledge of either is required.

**Difficulty Level**
Intermediate

**Comment by Janaki2399** [comment]
I would like to contribute to this issue.Can you please elaborate more on the task? I am new to web development.

**Comment by und3fined-v01d** [comment]
Glad for your response. Going through Gatsby documentation would be a good start. I hope you are familiar with the basics of web development and understand descent level HTML, CSS and JS

**Comment by Janaki2399** [comment]
yes, I am familiar with the basics.

**Comment by und3fined-v01d** [comment]
Awesome...let me knoe if you need any help. You can fork the repo, create a separate branch and raise a PR and commit small patches for me to review and leave my feedback

**Comment by und3fined-v01d** [comment]
Start with a small patch that does nothing but set up Gatsby🙃

**Comment by Janaki2399** [comment]
Okay Soham I will do it.I will let you know if i need any help.

**Comment by rahulii** [comment]
hello @und3fined-v01d i would like to contribute.

**Comment by und3fined-v01d** [comment]
Please feel free to create a PR @rahulii

**Comment by amrita41** [comment]
I would like to contribute to this issue.

**Comment by rahul799** [comment]
Go ahead guys.

**Comment by kashish609jain** [comment]
I want to contribute in it . Please tell me what I need to do on it

**Comment by kashish609jain** [comment]
I also want to contribute in it, please tell me what I need to do ?

**Comment by rahulii** [comment]
@und3fined-v01d should i create a new folder in existing repo and start my work?
The existing repo conatins some boilerplate code in other languages,so how should i begin?

**Comment by sladyn98** [comment]
@und3fined-v01d would we like this feature to be a separate repository or just add it here itself, it would be great if we had a new repo for our website don't you think ?

**Comment by und3fined-v01d** [comment]
Yes I think we should make a separate repo. That is a good idea

**Comment by rahul799** [comment]
Yes. @und3fined-v01d would you like to do that?

**Comment by und3fined-v01d** [comment]
Yeah sure, I'll link a link to that repo here for those following it.

**Comment by und3fined-v01d** [comment]
We have created a new repo for this issue

**Comment by rahulii** [comment]
@und3fined-v01d can you provide link?

**Comment by und3fined-v01d** [comment]
Here is the link to the repo for this issue:

https://github.com/The-Codesis/codesis-website

**Comment by imabhinav7728** [comment]
I would love to contribute to this website, know the basics of HTML, CSS, bootstrap, and javascript. Please tell me what to do as I had not contributed to any project before.

**Comment by und3fined-v01d** [comment]
We have shifted this project as a separate repo. Please find the repo link above

**Comment by NidhiKJha** [comment]
@und3fined-v01d @rahul799 I don't think we should keep this issue open as we have already started the website task. Let's close it for now?

**Comment by und3fined-v01d** [comment]
Sure
