### ISSUE TITLE
Add link to Discord channel inside README.md

### ISSUE THREAD

**Issue by adiaholic** [The-Codesis/simple-static-website#39]
New contributors who directly stumble upon this repository should be able to navigate their way to our Discord channel.

**Comment by Scramjet911** [comment]
Can I work on this issue?

**Comment by adiaholic** [comment]
> @adiaholic Can I work on this issue?

Go for it!

**Comment by pranshi112** [comment]
Is the issue available?

**Comment by Scramjet911** [comment]
Added a PR #41

**Comment by adiaholic** [comment]
Solved under #47
