### ISSUE TITLE
Add the usage of git squash in README.md

### ISSUE THREAD

**Issue by tushar5526** [The-Codesis/simple-static-website#44]
For small features or bug fixes, almost everyone prefers a single commit to keep the history clean.

Explain how we use `git squash` to combine multiple commits into one commit.

You can refer to [this](https://www.freecodecamp.org/forum/t/how-to-squash-multiple-commits-into-one-with-git-squash/13231)

**Comment by pranshi112** [comment]
Can I work on this issue?

**Comment by adiaholic** [comment]
@pranshi112 sure.
